const types = {
    WRITE_TODO: 'WRITE_TODO',
    SELECT_TODO: 'SELECT_TODO',
    UNSELECT_TODO: 'UNSELECT_TODO',
    MODIFY_TODO: 'MODIFY_TODO',
    DELETE_TODO: 'DELETE_TODO',
    PWCHECKFORMODIFY: 'PWCHECKFORMODIFY',
    PWCHECKFORDELETE: 'PWCHECKFORDELETE',
    PWCHECKCANCEL: 'PWCHECKCANCEL',
    WRITE_COMMENT: 'WRITE_COMMENT',
    PRESS_LIKE: 'PRESS_LIKE',
    PREV_VIEW: 'PREV_VIEW',
    NEXT_VIEW: 'NEXT_VIEW',
};

export default types;