const types = {
    WRITE_TODO: 'WRITE_TODO',
    SELECT_TODO: 'SELECT_TODO',
    UNSELECT_TODO: 'UNSELECT_TODO',
    MODIFY_TODO: 'MODIFY_TODO',
    DELETE_TODO: 'DELETE_TODO',
    PWCHECKFORMODIFY: 'PWCHECKFORMODIFY',
    PWCHECKFORDELETE: 'PWCHECKFORDELETE',
    PWCHECKCANCEL: 'PWCHECKCANCEL',
};

export default types;